name: Open Pull Request to merge changes to kusama branch

on:
  push:
    branches:
      - polkadot

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout polkadot
        uses: actions/checkout@v3
        with:
          ref: kusama
      - name: Reset promotion branch
        run: |
          git fetch origin polkadot:polkadot
          git reset --hard polkadot
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Merge polkadot branch to kusama'
          body: 'This pull request merges the polkadot branch to the kusama branch.'
          branch: kusama-sync
          delete-branch: true
